// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package tutorial

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID          int64
	AggregateID int32
	Kind        string
	Version     string
	CreatedAt   pgtype.Timestamptz
	Data        []byte
}

type User struct {
	ID        int64
	Name      string
	Password  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
